//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFMovieProject
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class UserData
    {
        [Required(ErrorMessage = "Username cannot be empty")]
        [MinLength(3, ErrorMessage = "Username should be of min 3 chars")]
        public string username { get; set; }
        [Required]
        
        [RegularExpression("[0-9][0-9][0-9][0-9]", ErrorMessage = "Invalid password format")]
        public string password { get; set; }

        [NotMapped]
        [Compare("password",ErrorMessage ="Pls reenter password....It should match with password")]
        public string retypepassword { get; set; }

    }
}
