//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyProduct
    {
        public int productid { get; set; }
        public string productname { get; set; }
        public Nullable<decimal> unitprice { get; set; }
        public Nullable<int> Monthly_Sales { get; set; }
    }
}
