//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCLoginRegistrationEg
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tblMovie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblMovie()
        {
            this.tblDiscs = new HashSet<tblDisc>();
        }
    
        public int id { get; set; }
        [Required(ErrorMessage ="Movie Name should not be null")]
        [DisplayName("Movie Name")]
        public string name { get; set; }
        [Range(0,4,ErrorMessage ="Duration cannot be greater than 3 hrs")]
        [DisplayName("Movie Duration")]
        public Nullable<double> duration { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDisc> tblDiscs { get; set; }
    }
}
